version: '3.9'
services:

  redis:
    image: redis:latest
    container_name: redis-thumbnail
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data

  app:
    build: .
    container_name: thumbnail
    image: app
    ports:
      - "9090:9090"
    depends_on:
      - redis
